/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigGuide: typeof import('./src/components/ConfigGuide.vue')['default']
    FilterControls: typeof import('./src/components/FilterControls.vue')['default']
    FlapTable: typeof import('./src/components/FlapTable.vue')['default']
    IBiArrowClockwise: typeof import('~icons/bi/arrow-clockwise')['default']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiClockHistory: typeof import('~icons/bi/clock-history')['default']
    IBiExclamationTriangle: typeof import('~icons/bi/exclamation-triangle')['default']
    IBiFiletypeJson: typeof import('~icons/bi/filetype-json')['default']
    IBiHddRack: typeof import('~icons/bi/hdd-rack')['default']
    IBiLink: typeof import('~icons/bi/link')['default']
    IBiTerminal: typeof import('~icons/bi/terminal')['default']
    ServerList: typeof import('./src/components/ServerList.vue')['default']
    StatusCard: typeof import('./src/components/StatusCard.vue')['default']
  }
}
